/**
 * CMS Summary
 */
export const GET_ALL_CAR = "GET_ALL_CAR";
export const GET_ALL_CAR_SUCCESS = "GET_ALL_CAR_SUCCESS";
export const GET_ALL_CAR_FAILURE = "GET_ALL_CAR_FAILURE";

export const GET_CATEGORY = "GET_CATEGORY";
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_FAILURE = "GET_CATEGORY_FAILURE";

export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE";

export const GET_MAKES = "GET_MAKES";
export const GET_MAKES_SUCCESS = "GET_MAKES_SUCCESS";
export const GET_MAKES_FAILURE = "GET_MAKES_FAILURE";

export const GET_MODELS = "GET_MODELS";
export const GET_MODELS_SUCCESS = "GET_MODELS_SUCCESS";
export const GET_MODELS_FAILURE = "GET_MODELS_FAILURE";
