export const SIGNUP_USER = "SIGNUP_USER";
export const SIGNUP_USER_SUCCESS = "SIGNUP_USER_SUCCESS";
export const SIGNUP_USER_FAILURE = "SIGNUP_USER_FAILURE";

export const HANDLE_REGISTER_FORM = "HANDLE_REGISTER_FORM";

export const HANDLE_REGISTER_ERROR = "HANDLE_REGISTER_ERROR";
export const HANDLE_REGISTER_SUCCESS = "HANDLE_REGISTER_SUCCESS";
export const HANDLE_REGISTER_WARNING = "HANDLE_REGISTER_WARNING";

export const HANDLE_RESET_SUCCESS = "HANDLE_RESET_SUCCESS";
