export const GET_ALL_ONLINEPAYMENT = "GET_ALL_ONLINEPAYMENT";
export const GET_ALL_ONLINEPAYMENT_SUCCESS = "GET_ALL_ONLINEPAYMENT_SUCCESS";
export const GET_ALL_ONLINEPAYMENT_FAILURE = "GET_ALL_ONLINEPAYMENT_FAILURE";

export const EXPORT_ONLINEPAYMENT = "EXPORT_ONLINEPAYMENT";
export const EXPORT_ONLINEPAYMENT_SUCCESS = "EXPORT_ONLINEPAYMENT_SUCCESS";
export const EXPORT_ONLINEPAYMENT_FAILURE = "EXPORT_ONLINEPAYMENT_FAILURE";