export const GET_ALL_FEATURED = "GET_ALL_FEATURED";
export const GET_ALL_FEATURED_FAILURE = "GET_ALL_FEATURED_FAILURE";
export const GET_ALL_FEATURED_SUCCESS = "GET_ALL_FEATURED_SUCCESS";

export const GET_FEATURED_CHILDREN = "GET_FEATURED_CHILDREN";
export const GET_FEATURED_CHILDREN_SUCCESS = "GET_FEATURED_CHILDREN_SUCCESS";
export const GET_FEATURED_CHILDREN_FAILURE = "GET_FEATURED_CHILDREN_FAILURE";

export const NEW_FEATURED_SECTION = "NEW_FEATURED_SECTION";
export const NEW_FEATURED_SECTION_FAILURE = "NEW_FEATURED_SECTION_FAILURE";
export const NEW_FEATURED_SECTION_SUCCESS = "NEW_FEATURED_SECTION_SUCCESS";

export const NEW_FEATURED_CAR = "NEW_FEATURED_CAR";
export const NEW_FEATURED_CAR_FAILURE = "NEW_FEATURED_CAR_FAILURE";
export const NEW_FEATURED_CAR_SUCCESS = "NEW_FEATURED_CAR_SUCCESS";

export const EDIT_FEATURED_SECTION = "EDIT_FEATURED_SECTION";
export const EDIT_FEATURED_SECTION_SUCCESS = "EDIT_FEATURED_SECTION_SUCCESS";
export const EDIT_FEATURED_SECTION_FAILURE = "EDIT_FEATURED_SECTION_FAILURE";

export const EDIT_FEATURED_CAR = "EDIT_FEATURED_CAR";
export const EDIT_FEATURED_CAR_SUCCESS = "EDIT_FEATURED_CAR_SUCCESS";
export const EDIT_FEATURED_CAR_FAILURE = "EDIT_FEATURED_CAR_FAILURE";

export const DELETE_FEATURED_SECTION = "DELETE_FEATURED_SECTION";
export const DELETE_FEATURED_SECTION_SUCCESS = "DELETE_FEATURED_SECTION_SUCCESS";
export const DELETE_FEATURED_SECTION_FAILURE = "DELETE_FEATURED_SECTION_FAILURE";

export const DELETE_FEATURED_CAR = "DELETE_FEATURED_CAR";
export const DELETE_FEATURED_CAR_SUCCESS = "DELETE_FEATURED_CAR_SUCCESS";
export const DELETE_FEATURED_CAR_FAILURE = "DELETE_FEATURED_CAR_FAILURE";