export const GET_ALL_FOOTER = "GET_ALL_FOOTER";
export const GET_ALL_FOOTER_FAILURE = "GET_ALL_FOOTER_FAILURE";
export const GET_ALL_FOOTER_SUCCESS = "GET_ALL_FOOTER_SUCCESS";

export const GET_FOOTER_CHILDREN = "GET_FOOTER_CHILDREN";
export const GET_FOOTER_CHILDREN_SUCCESS = "GET_FOOTER_CHILDREN_SUCCESS";
export const GET_FOOTER_CHILDREN_FAILURE = "GET_FOOTER_CHILDREN_FAILURE";

export const NEW_FOOTER_SECTION = "NEW_FOOTER_SECTION";
export const NEW_FOOTER_SECTION_FAILURE = "NEW_FOOTER_SECTION_FAILURE";
export const NEW_FOOTER_SECTION_SUCCESS = "NEW_FOOTER_SECTION_SUCCESS";

export const NEW_FOOTER_CAR = "NEW_FOOTER_CAR";
export const NEW_FOOTER_CAR_FAILURE = "NEW_FOOTER_CAR_FAILURE";
export const NEW_FOOTER_CAR_SUCCESS = "NEW_FOOTER_CAR_SUCCESS";

export const EDIT_FOOTER_SECTION = "EDIT_FOOTER_SECTION";
export const EDIT_FOOTER_SECTION_SUCCESS = "EDIT_FOOTER_SECTION_SUCCESS";
export const EDIT_FOOTER_SECTION_FAILURE = "EDIT_FOOTER_SECTION_FAILURE";

export const EDIT_FOOTER_CAR = "EDIT_FOOTER_CAR";
export const EDIT_FOOTER_CAR_SUCCESS = "EDIT_FOOTER_CAR_SUCCESS";
export const EDIT_FOOTER_CAR_FAILURE = "EDIT_FOOTER_CAR_FAILURE";

export const DELETE_FOOTER_SECTION = "DELETE_FOOTER_SECTION";
export const DELETE_FOOTER_SECTION_SUCCESS = "DELETE_FOOTER_SECTION_SUCCESS";
export const DELETE_FOOTER_SECTION_FAILURE = "DELETE_FOOTERD_SECTION_FAILURE";

export const DELETE_FOOTER_CAR = "DELETE_FOOTER_CAR";
export const DELETE_FOOTER_CAR_SUCCESS = "DELETE_FOOTER_CAR_SUCCESS";
export const DELETE_FOOTER_CAR_FAILURE = "DELETE_FOOTER_CAR_FAILURE";