export const GET_RENTAL_CAR = "GET_RENTAL_CAR";
export const GET_RENTAL_CAR_SUCCESS = "GET_RENTAL_CAR_SUCCESS";
export const GET_RENTAL_CAR_FAILURE = "GET_RENTAL_CAR_FAILURE";

export const CREATE_RENTAL_CAR = "CREATE_RENTAL_CAR";
export const CREATE_RENTAL_CAR_SUCCESS = "CREATE_RENTAL_CAR_SUCCESS";
export const CREATE_RENTAL_CAR_FAILURE = "CREATE_RENTAL_CAR_FAILURE";

export const UPDATE_RENTAL_CAR = "UPDATE_RENTAL_CAR";
export const UPDATE_RENTAL_CAR_SUCCESS = "UPDATE_RENTAL_CAR_SUCCESS";
export const UPDATE_RENTAL_CAR_FAILURE = "UPDATE_RENTAL_CAR_FAILURE";

export const DELETE_RENTAL_CAR = "DELETE_RENTAL_CAR";
export const DELETE_RENTAL_CAR_SUCCESS = "DELETE_RENTAL_CAR_SUCCESS";
export const DELETE_RENTAL_CAR_FAILURE = "DELETE_RENTAL_CAR_FAILURE";

export const GET_RENTAL_CATEGORY = "GET_RENTAL_CATEGORY";
export const GET_RENTAL_CATEGORY_SUCCESS = "GET_RENTAL_CATEGORY_SUCCESS";
export const GET_RENTAL_CATEGORY_FAILURE = "GET_RENTAL_CATEGORY_FAILURE";
