// Get Campaign list
export const GET_ALL_CAMPAIGN = "GET_ALL_CAMPAIGN";
export const GET_ALL_CAMPAIGN_SUCCESS = "GET_ALL_CAMPAIGN_SUCCESS";
export const GET_ALL_CAMPAIGN_FAILURE = "GET_ALL_CAMPAIGN_FAILURE";

// Get Campaign list with reports and details
export const GET_CAMPAIGN = "GET_CAMPAIGN";
export const GET_CAMPAIGN_SUCCESS = "GET_CAMPAIGN_SUCCESS";
export const GET_CAMPAIGN_FAILURE = "GET_CAMPAIGN_FAILURE";

// Create Campaign
export const NEW_CAMPAIGN = "NEW_CAMPAIGN";
export const NEW_CAMPAIGN_SUCCESS = "NEW_CAMPAIGN_SUCCESS";
export const NEW_CAMPAIGN_FAILURE = "NEW_CAMPAIGN_FAILURE";

// Close Success Dialog
export const CLOSE_CAMPAIGN_SUCCESS = "CLOSE_CAMPAIGN_SUCCESS";

// Send Campaign Now
export const SEND_CAMPAIGN_NOW = "SEND_CAMPAIGN_NOW";
export const SEND_CAMPAIGN_NOW_SUCCESS = "SEND_CAMPAIGN_NOW_SUCCESS";
export const SEND_CAMPAIGN_NOW_FAILURE = "SEND_CAMPAIGN_NOW_FAILURE";

// Delete Campaign
export const DELETE_CAMPAIGN = "DELETE_CAMPAIGN";
export const DELETE_CAMPAIGN_SUCCESS = "DELETE_CAMPAIGN_SUCCESS";
export const DELETE_CAMPAIGN_FAILURE = "DELETE_CAMPAIGN_FAILURE";
