/**
 * Deal Actions
 */

// List
export const CHANGE_DEAL_LIST_VIEW = "CHANGE_DEAL_LIST_VIEW";
export const GET_DEAL_FAILURE = "GET_DEAL_FAILURE";
export const GET_DEAL_SUCCESS = "GET_DEAL_SUCCESS";
export const GET_ALL_DEAL = "GET_ALL_DEAL";
export const GET_MY_DEAL = "GET_MY_DEAL";
export const GET_OPEN_DEAL = "GET_OPEN_DEAL";
export const GET_CLOSED_DEAL = "GET_CLOSED_DEAL";
export const GET_WON_DEAL = "GET_WON_DEAL";

// List Summary
export const GET_DEAL_SUMMARY = "GET_DEAL_SUMMARY";
export const GET_DEAL_SUMMARY_SUCCESS = "GET_DEAL_SUMMARY_SUCCESS";
export const GET_DEAL_SUMMARY_FAILURE = "GET_DEAL_SUMMARY_FAILURE";

// View
export const GET_SINGLE_DEAL = "GET_SINGLE_DEAL";
export const GET_SINGLE_DEAL_SUCCESS = "GET_SINGLE_DEAL_SUCCESS";
export const CLEAR_SINGLE_DEAL = "CLEAR_SINGLE_DEAL";

// New
export const NEW_DEAL = "NEW_DEAL";
export const NEW_DEAL_SUCCESS = "NEW_DEAL_SUCCESS";
export const NEW_DEAL_FAILURE = "NEW_DEAL_FAILURE";

// Edit
export const EDIT_DEAL = "EDIT_DEAL";
export const EDIT_DEAL_SUCCESS = "EDIT_DEAL_SUCCESS";
export const EDIT_DEAL_FAILURE = "EDIT_DEAL_FAILURE";

// Form Fields
export const GET_DEAL_FORM_FIELDS = "GET_DEAL_FORM_FIELDS";
export const GET_DEAL_FORM_SUCCESS = "GET_DEAL_FORM_SUCCESS";
export const GET_DEAL_FORM_FAILURE = "GET_DEAL_FORM_FAILURE";

// Deal Stage Stepper
export const ON_CLICK_STEP = "ON_CLICK_STEP";
export const SET_CURRENT_STEP = "SET_CURRENT_STEP";
export const ON_CHANGE_STEP_STATE = "ON_CHANGE_STEP_STATE";
export const ON_SUBMIT_NEW_STAGE = "ON_SUBMIT_NEW_STAGE";
export const ON_SUBMIT_NEW_STAGE_SUCCESS = "ON_SUBMIT_NEW_STAGE_SUCCESS";
export const ON_SUBMIT_NEW_STAGE_FAILURE = "ON_SUBMIT_NEW_STAGE_FAILURE";

// Delete
export const DELETE_DEAL = "DELETE_DEAL";
export const DELETE_DEAL_SUCCESS = "DELETE_DEAL_SUCCESS";
export const DELETE_DEAL_FAILURE = "DELETE_DEAL_FAILURE";

// Notes
export const ADD_NOTE_DEAL = "ADD_NOTE_DEAL";
export const ADD_NOTE_DEAL_SUCCESS = "ADD_NOTE_DEAL_SUCCESS";
export const ADD_NOTE_DEAL_FAILURE = "ADD_NOTE_DEAL_FAILURE";

// Transfer
export const TRANSFER_DEAL = "TRANSFER_DEAL";
export const TRANSFER_DEAL_SUCCESS = "TRANSFER_DEAL_SUCCESS";
export const TRANSFER_DEAL_FAILURE = "TRANSFER_DEAL_FAILURE";

// Events
export const ADD_DEAL_EVENT = "ADD_DEAL_EVENT";
