/**
 * Payment Actions
 */

// List
export const PAYMENT_LIST_DROPDOWN = "PAYMENT_LIST_DROPDOWN";
export const CHANGE_PAYMENT_LIST_VIEW = "CHANGE_PAYMENT_LIST_VIEW";
export const GET_PAYMENT_FAILURE = "GET_PAYMENT_FAILURE";
export const GET_PAYMENT_SUCCESS = "GET_PAYMENT_SUCCESS";
export const GET_ALL_PAYMENT = "GET_ALL_PAYMENT";
export const GET_MY_PAYMENT = "GET_MY_PAYMENT";
export const GET_OPEN_PAYMENT = "GET_OPEN_PAYMENT";
export const GET_CLOSED_PAYMENT = "GET_CLOSED_PAYMENT";

// View
export const GET_SINGLE_PAYMENT = "GET_SINGLE_PAYMENT";
export const GET_SINGLE_PAYMENT_SUCCESS = "GET_SINGLE_PAYMENT_SUCCESS";
export const CLEAR_SINGLE_PAYMENT = "CLEAR_SINGLE_PAYMENT";


export const MAKE_PAYMENT = "MAKE_PAYMENT";
export const MAKE_PAYMENT_SUCCESS = "MAKE_PAYMENT_SUCCESS";
export const MAKE_PAYMENT_FAILURE = "MAKE_PAYMENT_FAILURE";

export const MAKE_PAYMENT_INCOMPLETE_FAILURE = "MAKE_PAYMENT_INCOMPLETE_FAILURE";
export const FETCH_ALL_PAYMENT = "FETCH_ALL_PAYMENT";

export const FETCH_ALL_PAYMENT_SUCCESS = "FETCH_ALL_PAYMENT_SUCCESS";
export const FETCH_ALL_PAYMENT_FAILURE = "FETCH_ALL_PAYMENT_FAILURE";


export const GET_SINGLE_COMPANY_PAYMENT = "GET_SINGLE_COMPANY_PAYMENT";
export const GET_SINGLE_COMPANY_PAYMENT_SUCCESS = "GET_SINGLE_COMPANY_PAYMENT_SUCCESS";
export const GET_SINGLE_COMPANY_PAYMENT_FAILURE = "GET_SINGLE_COMPANY_PAYMENT_FAILURE";


export const FETCH_ALL_COMPANINES = "FETCH_ALL_COMPANINES";
export const FETCH_ALL_COMPANINES_SUCCESS = "FETCH_ALL_COMPANINES_SUCCESS";
export const FETCH_ALL_COMPANINES_FAILURE = "FETCH_ALL_COMPANINES_FAILURE";


export const FETCH_ALL_INVOICES_COMPANINES = "FETCH_ALL_INVOICES_COMPANINES";
export const FETCH_ALL_INVOICES_COMPANINES_SUCCESS = "FETCH_ALL_INVOICES_COMPANINES_SUCCESS";
export const FETCH_ALL_INVOICES_COMPANINES_FAILURE = "FETCH_ALL_INVOICES_COMPANINES_FAILURE";



