/**
 * Invoice Actions
 */
// List
export const INVOICE_LIST_DROPDOWN = "INVOICE_LIST_DROPDOWN";
export const TOGGLE_INVOICE_SUMMARY = "TOGGLE_INVOICE_SUMMARY";
export const CHANGE_INVOICE_LIST_VIEW = "CHANGE_INVOICE_LIST_VIEW";
export const GET_INVOICE_FAILURE = "GET_INVOICE_FAILURE";
export const GET_INVOICE_SUCCESS = "GET_INVOICE_SUCCESS";
export const GET_ALL_INVOICE = "GET_ALL_INVOICE";
export const GET_MY_INVOICE = "GET_MY_INVOICE";
export const GET_OPEN_INVOICE = "GET_OPEN_INVOICE";
export const GET_CLOSED_INVOICE = "GET_CLOSED_INVOICE";


// List Summary
export const GET_INVOICE_SUMMARY = "GET_INVOICE_SUMMARY";
export const GET_INVOICE_SUMMARY_SUCCESS = "GET_INVOICE_SUMMARY_SUCCESS";
export const GET_INVOICE_SUMMARY_FAILURE = "GET_INVOICE_SUMMARY_FAILURE";

// View
export const GET_SINGLE_INVOICE = "GET_SINGLE_INVOICE";
export const GET_SINGLE_INVOICE_SUCCESS = "GET_SINGLE_INVOICE_SUCCESS";
export const CLEAR_SINGLE_INVOICE = "CLEAR_SINGLE_INVOICE";


export const DELETE_INVOICE = "DELETE_INVOICE";
export const DELETE_INVOICE_SUCCESS = "DELETE_INVOICE_SUCCESS";
export const DELETE_INVOICE_FAILURE = "DELETE_INVOICE_FAILURE";

export const INVOICE_HANDLE_STATE_UPDATE = "INVOICE_HANDLE_STATE_UPDATE";
export const INVOICE_HANDLE_STATE_UPDATE_SUCCESS = "INVOICE_HANDLE_STATE_UPDATE_SUCCESS";
export const INVOICE_HANDLE_STATE_UPDATE_FAILURE = "DELETE_INVOICE_FAILURE";

export const INVOICE_HANDLE_STATE_CREATE_NEW_VERSION = "INVOICE_HANDLE_STATE_CREATE_NEW_VERSION";
export const INVOICE_HANDLE_STATE_REVERT_PREVIOUS_VERSION = "INVOICE_HANDLE_STATE_REVERT_PREVIOUS_VERSION";

export const SUBMIT_INVOICE = "SUBMIT_INVOICE";
export const SUBMIT_INVOICE_SUCCESS = "SUBMIT_INVOICE_SUCCESS";
export const SUBMIT_INVOICE_FAILURE = "SUBMIT_INVOICE_FAILURE";


export const SUBMIT_NEW_INVOICE = "SUBMIT_NEW_INVOICE";
export const SUBMIT_NEW_INVOICE_SUCCESS = "SUBMIT_NEW_INVOICE_SUCCESS";
export const SUBMIT_NEW_INVOICE_FAILURE = "SUBMIT_NEW_INVOICE_FAILURE";

export const RESTART_UPLOAD_STATUS = "RESTART_UPLOAD_STATUS";











