/**
 * Credit Note Actions
*/


// Fetch All Credit Notes
export const GET_ALL_CREDIT_NOTE = "GET_ALL_CREDIT_NOTE";
export const GET_ALL_CREDIT_NOTE_SUCCESS = "GET_ALL_CREDIT_NOTE_SUCCESS";
export const GET_ALL_CREDIT_NOTE_FAILTURE = "GET_ALL_CREDIT_NOTE_FAILTURE";

// View
export const GET_SINGLE_CREDIT_NOTE = "GET_SINGLE_CREDIT_NOTE";
export const GET_SINGLE_CREDIT_NOTE_SUCCESS = "GET_SINGLE_CREDIT_NOTE_SUCCESS";
export const GET_SINGLE_CREDIT_NOTE_FAILURE = "GET_SINGLE_CREDIT_NOTE_FAILURE";

// Post
export const POST_SINGLE_CREDIT_NOTE = "POST_SINGLE_CREDIT_NOTE";
export const POST_SINGLE_CREDIT_NOTE_SUCCESS = "POST_SINGLE_CREDIT_NOTE_SUCCESS";
export const POST_SINGLE_CREDIT_NOTE_FAILURE = "POST_SINGLE_CREDIT_NOTE_FAILURE";

// Convert
export const CONVERT_SINGLE_CREDIT_NOTE = "CONVERT_SINGLE_CREDIT_NOTE";
export const CONVERT_SINGLE_CREDIT_NOTE_SUCCESS = "CONVERT_SINGLE_CREDIT_NOTE_SUCCESS";
export const CONVERT_SINGLE_CREDIT_NOTE_FAILURE = "CONVERT_SINGLE_CREDIT_NOTE_FAILURE";







