/**
 * CMS Summary
 */
export const GET_ALL_CMSPAGES = "GET_ALL_CMSPAGES";
export const GET_ALL_CMSPAGES_SUCCESS = "GET_ALL_CMSPAGES_SUCCESS";
export const GET_ALL_CMSPAGES_FAILURE = "GET_ALL_CMSPAGES_FAILURE";

export const GET_SINGLE_CMSPAGE = "GET_SINGLE_CMSPAGE";
export const GET_SINGLE_CMSPAGE_SUCCESS = "GET_SINGLE_CMSPAGE_SUCCESS";
export const GET_SINGLE_CMSPAGE_FAILURE = "GET_SINGLE_CMSPAGE_FAILURE";

export const NEW_CMSPAGE = "NEW_CMSPAGE";
export const NEW_CMSPAGE_SUCCESS = "NEW_CMSPAGE_SUCCESS";
export const NEW_CMSPAGE_FAILURE = "NEW_CMSPAGE_FAILURE";

export const UPDATE_CMSPAGE = "UPDATE_CMSPAGE";
export const UPDATE_CMSPAGE_SUCCESS = "UPDATE_CMSPAGE_SUCCESS";
export const UPDATE_CMSPAGE_FAILURE = "UPDATE_CMSPAGE_FAILURE";

export const DELETE_CMSPAGE = "DELETE_CMSPAGE";
export const DELETE_CMSPAGE_SUCCESS = "DELETE_CMSPAGE_SUCCESS";
export const DELETE_CMSPAGE_FAILURE = "DELETE_CMSPAGE_FAILURE";
