/**
 * Website Setting Action Types
 */

// API Calls
export const GET_INTEREST_RATE = "GET_INTEREST_RATE";
export const GET_INTEREST_RATE_SUCCESS = "GET_INTEREST_RATE_SUCCESS";
export const GET_INTEREST_RATE_FAILURE = "GET_INTEREST_RATE_FAILURE";

export const UPDATE_INTEREST_RATE = "UPDATE_INTEREST_RATE";
export const UPDATE_INTEREST_RATE_SUCCESS = "UPDATE_INTEREST_RATE_SUCCESS";
export const UPDATE_INTEREST_RATE_FAILURE = "UPDATE_INTEREST_RATE_FAILURE";

export const ADD_INTEREST_RATE = "ADD_INTEREST_RATE";
export const ADD_INTEREST_RATE_SUCCESS = "ADD_INTEREST_RATE_SUCCESS";
export const ADD_INTEREST_RATE_FAILURE = "ADD_INTEREST_RATE_FAILURE";
