/**
 * Calendar Action Types
 */
export const GET_ALL_EVENTS = "GET_ALL_EVENTS";
export const GET_ALL_UPCOMING_EVENTS = "GET_ALL_UPCOMING_EVENTS";
export const GET_EVENT_SEARCH = "GET_EVENT_SEARCH";
export const GET_ALL_EVENTS_SUCCESS = "GET_ALL_EVENTS_SUCCESS";
export const GET_ALL_UPCOMING_EVENTS_SUCCESS = "GET_ALL_UPCOMING_EVENTS_SUCCESS";
export const GET_ALL_EVENTS_FAILURE = "GET_ALL_EVENTS_FAILURE";

export const GET_CALENDARSETTINGS = "GET_CALENDARSETTINGS";
export const GET_CALENDARSETTINGS_SUCCESS = "GET_CALENDARSETTINGS_SUCCESS";
export const GET_CALENDARSETTINGS_FAILURE = "GET_CALENDARSETTINGS_FAILURE";
export const UPDATE_CALENDARSETTINGS  = "UPDATE_CALENDARSETTINGS";
export const UPDATE_CALENDARSETTINGS_SUCCESS = "UPDATE_CALENDARSETTINGS_SUCCESS";
export const UPDATE_CALENDARSETTINGS_FAILURE = "UPDATE_CALENDARSETTINGS_FAILURE";
export const NEW_CALENDARSETTING = "NEW_CALENDARSETTING";
export const NEW_CALENDARSETTING_SUCCESS = "NEW_CALENDARSETTING_SUCCESS";
export const NEW_CALENDARSETTING_FAILURE = "NEW_CALENDARSETTING_FAILURE";
export const DELETE_CALENDARSETTING = "DELETE_CALENDARSETTING";
export const DELETE_CALENDARSETTING_SUCCESS = "DELETE_CALENDARSETTING_SUCCESS";
export const DELETE_CALENDARSETTING_FAILURE = "DELETE_CALENDARSETTING_FAILURE";

export const ADD_EVENT = "ADD_EVENT";
export const ADD_EVENT_SUCCESS = "ADD_EVENT_SUCCESS";
export const ADD_EVENT_FAILURE = "ADD_EVENT_FAILURE";

export const UPDATE_EVENT = "UPDATE_EVENT";
export const UPDATE_EVENT_SUCCESS = "UPDATE_EVENT_SUCCESS";
export const UPDATE_EVENT_FAILURE = "UPDATE_EVENT_FAILURE";

export const DELETE_EVENT = "DELETE_EVENT";
export const DELETE_EVENT_SUCCESS = "DELETE_EVENT_SUCCESS";
export const DELETE_EVENT_FAILURE = "DELETE_EVENT_FAILURE";

export const GET_EVENT_FAILURE = "GET_EVENT_FAILURE";
