export const GET_ALL_MAILING_LIST = "GET_ALL_MAILING_LIST";
export const GET_ALL_MAILING_LIST_SUCCESS = "GET_ALL_MAILING_LIST_SUCCESS";
export const GET_ALL_MAILING_LIST_FAILURE = "GET_ALL_MAILING_LIST_FAILURE";

export const GET_ALL_ADMIN_MAILING_LIST = "GET_ALL_ADMIN_MAILING_LIST";
export const GET_ALL_ADMIN_MAILING_LIST_SUCCESS =
  "GET_ALL_ADMIN_MAILING_LIST_SUCCESS";
export const GET_ALL_ADMIN_MAILING_LIST_FAILURE =
  "GET_ALL_ADMIN_MAILING_LIST_FAILURE";

export const GET_MAILING_LIST = "GET_MAILING_LIST";
export const GET_MAILING_LIST_SUCCESS = "GET_MAILING_LIST_SUCCESS";
export const GET_MAILING_LIST_FAILURE = "GET_MAILING_LIST_FAILURE";

export const GET_CONTACTS = "GET_CONTACTS";
export const GET_CONTACTS_SUCCESS = "GET_CONTACTS_SUCCESS";
export const GET_CONTACTS_FAILURE = "GET_CONTACTS_FAILURE";

// Save to Mailing List
export const SAVE_TO_MAILING_LIST = "SAVE_TO_MAILING_LIST";
export const SAVE_TO_MAILING_LIST_SUCCESS = "SAVE_TO_MAILING_LIST_SUCCESS";
export const SAVE_TO_MAILING_LIST_FAILURE = "SAVE_TO_MAILING_LIST_FAILURE";

// Remove from Mailing List
export const REMOVE_FROM_MAILING_LIST = "REMOVE_FROM_MAILING_LIST";
export const REMOVE_FROM_MAILING_LIST_SUCCESS =
  "REMOVE_FROM_MAILING_LIST_SUCCESS";
export const REMOVE_FROM_MAILING_LIST_FAILURE =
  "REMOVE_FROM_MAILING_LIST_FAILURE";

// Create List
export const CREATE_MAILING_LIST = "CREATE_MAILING_LIST";
export const CREATE_MAILING_LIST_SUCCESS = "CREATE_MAILING_LIST_SUCCESS";
export const CREATE_MAILING_LIST_FAILURE = "CREATE_MAILING_LIST_FAILURE";
// Update List
export const UPDATE_MAILING_LIST = "UPDATE_MAILING_LIST";
export const UPDATE_MAILING_LIST_SUCCESS = "UPDATE_MAILING_LIST_SUCCESS";
export const UPDATE_MAILING_LIST_FAILURE = "UPDATE_MAILING_LIST_FAILURE";
// Delete List
export const DELETE_MAILING_LIST = "DELETE_MAILING_LIST";
export const DELETE_MAILING_LIST_SUCCESS = "DELETE_MAILING_LIST_SUCCESS";
export const DELETE_MAILING_LIST_FAILURE = "DELETE_MAILING_LIST_FAILURE";
