export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_ALL_PRODUCTS_FAILURE = "GET_ALL_PRODUCTS_FAILURE";
export const GET_ALL_PRODUCTS_SUCCESS = "GET_ALL_PRODUCTS_SUCCESS";

export const GET_ALL_PREOWNED_PRODUCTS = "GET_ALL_PREOWNED_PRODUCTS";
export const GET_ALL_PREOWNED_PRODUCTS_FAILURE = "GET_ALL_PREOWNED_PRODUCTS_FAILURE";
export const GET_ALL_PREOWNED_PRODUCTS_SUCCESS = "GET_ALL_PREOWNED_PRODUCTS_SUCCESS";