/**
 * CMS Summary
 */
export const GET_ALL_BLOG = "GET_ALL_BLOG";
export const GET_ALL_BLOG_SUCCESS = "GET_ALL_BLOG_SUCCESS";
export const GET_ALL_BLOG_FAILURE = "GET_ALL_BLOG_FAILURE";

export const GET_SINGLE_BLOG = "GET_SINGLE_BLOG";
export const GET_SINGLE_BLOG_SUCCESS = "GET_SINGLE_BLOG_SUCCESS";
export const GET_SINGLE_BLOG_FAILURE = "GET_SINGLE_BLOG_FAILURE";

export const NEW_BLOG = "NEW_BLOG";
export const NEW_BLOG_SUCCESS = "NEW_BLOG_SUCCESS";
export const NEW_BLOG_FAILURE = "NEW_BLOG_FAILURE";
