/**
 * Lead Actions
 */

// List
export const CHANGE_LEAD_LIST_VIEW = "CHANGE_LEAD_LIST_VIEW";
export const GET_LEAD_FAILURE = "GET_LEAD_FAILURE";
export const GET_LEAD_SUCCESS = "GET_LEAD_SUCCESS";
export const GET_ALL_LEAD = "GET_ALL_LEAD";
export const GET_MY_LEAD = "GET_MY_LEAD";
export const GET_OPEN_LEAD = "GET_OPEN_LEAD";
export const GET_HOT_LEAD = "GET_HOT_LEAD";
export const GET_COLD_LEAD = "GET_COLD_LEAD";

// List Summary
export const GET_LEAD_SUMMARY = "GET_LEAD_SUMMARY";
export const GET_LEAD_SUMMARY_SUCCESS = "GET_LEAD_SUMMARY_SUCCESS";
export const GET_LEAD_SUMMARY_FAILURE = "GET_LEAD_SUMMARY_FAILURE";

// View
export const GET_SINGLE_LEAD = "GET_SINGLE_LEAD";
export const GET_SINGLE_LEAD_SUCCESS = "GET_SINGLE_LEAD_SUCCESS";
export const CLEAR_SINGLE_LEAD = "CLEAR_SINGLE_LEAD";

// New
export const NEW_LEAD = "NEW_LEAD";
export const NEW_LEAD_SUCCESS = "NEW_LEAD_SUCCESS";
export const NEW_LEAD_FAILURE = "NEW_LEAD_FAILURE";

// Edit
export const EDIT_LEAD = "EDIT_LEAD";
export const EDIT_LEAD_SUCCESS = "EDIT_LEAD_SUCCESS";
export const EDIT_LEAD_FAILURE = "EDIT_LEAD_FAILURE";

// Fields
export const GET_LEADFORM_FIELDS = "GET_LEADFORM_FIELDS";
export const GET_LEADFORM_FIELDS_SUCCESS = "GET_LEADFORM_FIELDS_SUCCESS";
export const GET_LEADFORM_FIELDS_FAILURE = "GET_LEADFORM_FIELDS_FAILURE";

export const GET_LEADCONVERT_FIELDS = "GET_LEADCONVERT_FIELDS";
export const GET_LEADCONVERT_FIELDS_SUCCESS = "GET_LEADCONVERT_FIELDS_SUCCESS";
export const GET_LEADCONVERT_FIELDS_FAILURE = "GET_LEADCONVERT_FIELDS_FAILURE";

// Convert Lead
export const HANDLE_CONVERT_MODAL = "HANDLE_CONVERT_MODAL";
export const HANDLE_SUCCESS_CONVERT_MODAL = "HANDLE_SUCCESS_CONVERT_MODAL";
export const CONVERT_LEAD = "CONVERT_LEAD";
export const CONVERT_LEAD_SUCCESS = "CONVERT_LEAD_SUCCESS";
export const CONVERT_LEAD_FAILURE = "CONVERT_LEAD_FAILURE";
export const CHECK_ACCOUNT_EXIST = "CHECK_ACCOUNT_EXIST";
export const CHECK_ACCOUNT_EXIST_SUCCESS = "CHECK_ACCOUNT_EXIST_SUCCESS";
export const CHECK_ACCOUNT_EXIST_FAILURE = "CHECK_ACCOUNT_EXIST_FAILURE";

// Delete
export const DELETE_LEAD = "DELETE_LEAD";
export const DELETE_LEAD_SUCCESS = "DELETE_LEAD_SUCCESS";
export const DELETE_LEAD_FAILURE = "DELETE_LEAD_FAILURE";

// Notes
export const ADD_NOTE_LEAD = "ADD_NOTE_LEAD";
export const ADD_NOTE_LEAD_SUCCESS = "ADD_NOTE_LEAD_SUCCESS";
export const ADD_NOTE_LEAD_FAILURE = "ADD_NOTE_LEAD_FAILURE";

// Transfer
export const TRANSFER_LEAD = "TRANSFER_LEAD";
export const TRANSFER_LEAD_SUCCESS = "TRANSFER_LEAD_SUCCESS";
export const TRANSFER_LEAD_FAILURE = "TRANSFER_LEAD_FAILURE";

// Events
export const ADD_LEAD_EVENT = "ADD_LEAD_EVENT";
