/**
 * Website Setting Action Types
 */

// API Calls
export const GET_EMAIL_SETTINGS = "GET_EMAIL_SETTINGS";
export const GET_EMAIL_SETTINGS_SUCCESS = "GET_EMAIL_SETTINGS_SUCCESS";
export const GET_EMAIL_SETTINGS_FAILURE = "GET_EMAIL_SETTINGS_FAILURE";

export const SET_EMAIL_SETTINGS = "SET_EMAIL_SETTINGS";
export const SET_EMAIL_SETTINGS_SUCCESS = "SET_EMAIL_SETTINGS_SUCCESS";
export const SET_EMAIL_SETTINGS_FAILURE = "SET_EMAIL_SETTINGS_FAILURE";


export const UPDATE_EMAIL_SETTINGS = "UPDATE_EMAIL_SETTINGS";
export const UPDATE_EMAIL_SETTINGS_SUCCESS = "UPDATE_EMAIL_SETTINGS_SUCCESS";
export const UPDATE_EMAIL_SETTINGS_FAILURE = "UPDATE_EMAIL_SETTINGS_FAILURE";

export const DELETE_EMAIL_SETTINGS = "DELETE_EMAIL_SETTINGS";
export const DELETE_EMAIL_SETTINGS_SUCCESS = "DELETE_EMAIL_SETTINGS_SUCCESS";
export const DELETE_EMAIL_SETTINGS_FAILURE = "DELETE_EMAIL_SETTINGS_FAILURE";
