export const GET_ALL_BANNER = "GET_ALL_BANNER";
export const GET_ALL_BANNER_FAILURE = "GET_ALL_BANNER_FAILURE";
export const GET_ALL_BANNER_SUCCESS = "GET_ALL_BANNER_SUCCESS";

export const GET_SINGLE_BANNER = "GET_SINGLE_BANNER";
export const GET_SINGLE_BANNER_SUCCESS = "GET_SINGLE_BANNER_SUCCESS";
export const GET_SINGLE_BANNER_FAILURE = "GET_SINGLE_BANNER_FAILURE";

export const NEW_BANNER = "NEW_BANNER";
export const NEW_BANNER_SUCCESS = "NEW_BANNER_SUCCESS";
export const NEW_BANNER_FAILURE = "NEW_BANNER_FAILURE";

export const EDIT_BANNER = "EDIT_BANNER";
export const EDIT_BANNER_SUCCESS = "EDIT_BANNER_SUCCESS";
export const EDIT_BANNER_FAILURE = "EDIT_BANNER_FAILURE";

export const DELETE_BANNER = "DELETE_BANNER";
export const DELETE_BANNER_SUCCESS = "DELETE_BANNER_SUCCESS";
export const DELETE_BANNER_FAILURE = "DELETE_BANNER_FAILURE";