export const LOGIN_USER_RESENT_EMAIL = "LOGIN_USER_RESENT_EMAIL";
export const LOGIN_USER_RESENT_EMAIL_SUCCESS =
  "LOGIN_USER_RESENT_EMAIL_SUCCESS";
export const LOGIN_USER_RESENT_EMAIL_FAILURE =
  "LOGIN_USER_RESENT_EMAIL_FAILURE";

export const LOGIN_USER_RESET_PASSWORD = "LOGIN_USER_RESET_PASSWORD";
export const LOGIN_USER_RESET_PASSWORD_SUCCESS =
  "LOGIN_USER_RESET_PASSWORD_SUCCESS";
export const LOGIN_USER_RESET_PASSWORD_FAILURE =
  "LOGIN_USER_RESET_PASSWORD_FAILURE";
