export const GET_ALL_ANNOUNCEMENT = "GET_ALL_ANNOUNCEMENT";
export const GET_ALL_ANNOUNCEMENT_SUCCESS = "GET_ALL_ANNOUNCEMENT_SUCCESS";
export const GET_ALL_ANNOUNCEMENT_FAILURE = "GET_ALL_ANNOUNCEMENT_FAILURE";

export const NEW_ANNOUNCEMENT = "NEW_ANNOUNCEMENT";
export const NEW_ANNOUNCEMENT_SUCCESS = "NEW_ANNOUNCEMENT_SUCCESS";
export const NEW_ANNOUNCEMENT_FAILURE = "NEW_ANNOUNCEMENT_FAILURE";

export const EDIT_ANNOUNCEMENT = "EDIT_ANNOUNCEMENT";
export const EDIT_ANNOUNCEMENT_SUCCESS = "EDIT_ANNOUNCEMENT_SUCCESS";
export const EDIT_ANNOUNCEMENT_FAILURE = "EDIT_ANNOUNCEMENT_FAILURE";

export const DELETE_ANNOUNCEMENT = "DELETE_ANNOUNCEMENT";
export const DELETE_ANNOUNCEMENT_SUCCESS = "DELETE_ANNOUNCEMENT_SUCCESS";
export const DELETE_ANNOUNCEMENT_FAILURE = "DELETE_ANNOUNCEMENT_FAILURE";

export const GET_LATEST_ANNOUNCEMENT = "GET_LATEST_ANNOUNCEMENT";
export const GET_LATEST_ANNOUNCEMENT_SUCCESS =
  "GET_LATEST_ANNOUNCEMENT_SUCCESS";
export const GET_LATEST_ANNOUNCEMENT_FAILURE =
  "GET_LATEST_ANNOUNCEMENT_FAILURE";

export const READ_ANNOUNCEMENT = "READ_ANNOUNCEMENT";
export const READ_ANNOUNCEMENT_SUCCESS = "READ_ANNOUNCEMENT_SUCCESS";
export const READ_ANNOUNCEMENT_FAILURE = "READ_ANNOUNCEMENT_FAILURE";
