// Convert quotation to invoice
export const HANDLE_SUBMIT_ACCOUNT_QUOTATION_INVOICE = "HANDLE_SUBMIT_ACCOUNT_QUOTATION_INVOICE";
export const HANDLE_SUBMIT_ACCOUNT_QUOTATION_INVOICE_SUCCESS = "HANDLE_SUBMIT_ACCOUNT_QUOTATION_INVOICE_SUCCESS";
export const HANDLE_SUBMIT_ACCOUNT_QUOTATION_INVOICE_FAILURE = "HANDLE_SUBMIT_ACCOUNT_QUOTATION_INVOICE_FAILURE";
export const ACCOUNTING_CLEAR_STATE = "ACCOUNTING_CLEAR_STATE";


