export const GET_FOLLOWUP_RESULT = "GET_FOLLOWUP_RESULT";
export const GET_FOLLOWUP_RESULT_SUCCESS = "GET_FOLLOWUP_RESULT_SUCCESS";
export const GET_FOLLOWUP_RESULT_FAILURE = "GET_FOLLOWUP_RESULT_FAILURE";

export const EDIT_FOLLOWUP_RESULT = "EDIT_FOLLOWUP_RESULT";
export const EDIT_FOLLOWUP_RESULT_SUCCESS = "EDIT_FOLLOWUP_RESULT_SUCCESS";
export const EDIT_FOLLOWUP_RESULT_FAILURE = "EDIT_FOLLOWUP_RESULT_FAILURE";

export const DELETE_FOLLOWUP_RESULT = "DELETE_FOLLOWUP_RESULT";
export const DELETE_FOLLOWUP_RESULT_SUCCESS = "DELETE_FOLLOWUP_RESULT_SUCCESS";
export const DELETE_FOLLOWUP_RESULT_FAILURE = "DELETE_FOLLOWUP_RESULT_FAILURE";

export const ADD_FOLLOWUP_RESULT = "ADD_FOLLOWUP_RESULT";
export const ADD_FOLLOWUP_RESULT_SUCCESS = "ADD_FOLLOWUP_RESULT_SUCCESS";
export const ADD_FOLLOWUP_RESULT_FAILURE = "ADD_FOLLOWUP_RESULT_FAILURE";

export const GET_FOLLOWUP_TYPE = "GET_FOLLOWUP_TYPE";
export const GET_FOLLOWUP_TYPE_SUCCESS = "GET_FOLLOWUP_TYPE_SUCCESS";
export const GET_FOLLOWUP_TYPE_FAILURE = "GET_FOLLOWUP_TYPE_FAILURE";

export const DELETE_FOLLOWUP_TYPE = "DELETE_FOLLOWUP_TYPE";
export const DELETE_FOLLOWUP_TYPE_SUCCESS = "DELETE_FOLLOWUP_TYPE_SUCCESS";
export const DELETE_FOLLOWUP_TYPE_FAILURE = "DELETE_FOLLOWUP_TYPE_FAILURE";

export const ADD_FOLLOWUP_TYPE = "ADD_FOLLOWUP_TYPE";
export const ADD_FOLLOWUP_TYPE_SUCCESS = "ADD_FOLLOWUP_TYPE_SUCCESS";
export const ADD_FOLLOWUP_TYPE_FAILURE = "ADD_FOLLOWUP_TYPE_FAILURE";

export const EDIT_FOLLOWUP_TYPE = "EDIT_FOLLOWUP_TYPE";
export const EDIT_FOLLOWUP_TYPE_SUCCESS = "EDIT_FOLLOWUP_TYPE_SUCCESS";
export const EDIT_FOLLOWUP_TYPE_FAILURE = "EDIT_FOLLOWUP_TYPE_FAILURE";

export const NEW_FOLLOWUP = "NEW_FOLLOWUP";
export const NEW_FOLLOWUP_SUCCESS = "NEW_FOLLOWUP_SUCCESS";
export const NEW_FOLLOWUP_FAILURE = "NEW_FOLLOWUP_FAILURE";

export const EDIT_FOLLOWUP = "EDIT_FOLLOWUP";
export const EDIT_FOLLOWUP_SUCCESS = "EDIT_FOLLOWUP_SUCCESS";
export const EDIT_FOLLOWUP_FAILURE = "EDIT_FOLLOWUP_FAILURE";

export const DELETE_FOLLOWUP = "DELETE_FOLLOWUP";
export const DELETE_FOLLOWUP_SUCCESS = "DELETE_FOLLOWUP_SUCCESS";
export const DELETE_FOLLOWUP_FAILURE = "DELETE_FOLLOWUP_FAILURE";

export const EDIT_FOLLOWUP_COMPLETE = "EDIT_FOLLOWUP_COMPLETE";
export const EDIT_FOLLOWUP_COMPLETE_SUCCESS = "EDIT_FOLLOWUP_COMPLETE_SUCCESS";
export const EDIT_FOLLOWUP_COMPLETE_FAILURE = "EDIT_FOLLOWUP_COMPLETE_FAILURE";

// export const CHECK_FOLLOWUP_COMPLETE = "CHECK_FOLLOWUP_COMPLETE";
// export const CHECK_FOLLOWUP_COMPLETE_SUCCESS = "CHECK_FOLLOWUP_COMPLETE_SUCCESS";
// export const CHECK_FOLLOWUP_COMPLETE_FAILURE = "CHECK_FOLLOWUP_COMPLETE_FAILURE";
export const GET_FILTER_FOLLOWUP = "GET_FILTER_FOLLOWUP";
export const GET_FILTER_FOLLOWUP_SUCCESS = "GET_FILTER_FOLLOWUP_SUCCESS";
export const GET_FILTER_FOLLOWUP_FAILURE = "GET_FILTER_FOLLOWUP_FAILURE";
