export const GET_FOLLOWUP_RESULT = "GET_FOLLOWUP_RESULT";
export const GET_FOLLOWUP_RESULT_SUCCESS = "GET_FOLLOWUP_RESULT_SUCCESS";
export const GET_FOLLOWUP_RESULT_FAILURE = "GET_FOLLOWUP_RESULT_FAILURE";

export const GET_FOLLOWUP_TYPE = "GET_FOLLOWUP_TYPE";
export const GET_FOLLOWUP_TYPE_SUCCESS = "GET_FOLLOWUP_TYPE_SUCCESS";
export const GET_FOLLOWUP_TYPE_FAILURE = "GET_FOLLOWUP_TYPE_FAILURE";

export const NEW_FOLLOWUP = "NEW_FOLLOWUP";
export const NEW_FOLLOWUP_SUCCESS = "NEW_FOLLOWUP_SUCCESS";
export const NEW_FOLLOWUP_FAILURE = "NEW_FOLLOWUP_FAILURE";

export const EDIT_FOLLOWUP = "EDIT_FOLLOWUP";
export const EDIT_FOLLOWUP_SUCCESS = "EDIT_FOLLOWUP_SUCCESS";
export const EDIT_FOLLOWUP_FAILURE = "EDIT_FOLLOWUP_FAILURE";

export const DELETE_FOLLOWUP = "DELETE_FOLLOWUP";
export const DELETE_FOLLOWUP_SUCCESS = "DELETE_FOLLOWUP_SUCCESS";
export const DELETE_FOLLOWUP_FAILURE = "DELETE_FOLLOWUP_FAILURE";
