/**
 * Users Action Types
 */

//API Calls
export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_ALL_USERS_SUCCESS = "GET_USER_SUCCESS";

export const ON_CHANGE_ADD_USER = "ON_CHANGE_ADD_USER";
export const ADD_USER = "ADD_USER";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAILURE = "ADD_USER_FAILURE";

export const UPDATE_USER_START = "UPDATE_USER_START";
export const ON_CHANGE_UPDATE_USER = "ON_CHANGE_UPDATE_USER";
export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE";
export const ON_CHANGE_UPDATE_USER_RIGHTS = "ON_CHANGE_UPDATE_USER_RIGHTS";
export const UPDATE_USER_RIGHTS = "UPDATE_USER_RIGHTS";
export const UPDATE_USER_RIGHTS_SUCCESS = "UPDATE_USER_RIGHTS_SUCCESS";

export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";
export const GET_USER_PROFILE_END = "GET_USER_PROFILE_END";

export const GET_USER_FAILURE = "GET_USER_FAILURE";
