// Import
export const IMPORT_RECORD = "IMPORT_RECORD";
export const IMPORT_RECORD_SUCCESS = "IMPORT_RECORD_SUCCESS";
export const IMPORT_RECORD_FAILURE = "IMPORT_RECORD_FAILURE";

// Fetch mapping record
export const FETCH_IMPORT_MAPPING = "FETCH_IMPORT_MAPPING";
export const FETCH_IMPORT_MAPPING_SUCCESS = "FETCH_IMPORT_MAPPING_SUCCESS";
export const FETCH_IMPORT_MAPPING_FAILURE = "FETCH_IMPORT_MAPPING_FAILURE";
