export const GET_COMMISSION = "GET_COMMISSION";
export const GET_COMMISSION_SUCCESS = "GET_COMMISSION_SUCCESS";
export const GET_COMMISSION_FAILURE = "GET_COMMISSION_FAILURE";

export const CREATE_COMMISSION = "CREATE_COMMISSION";
export const CREATE_COMMISSION_SUCCESS = "CREATE_COMMISSION_SUCCESS";
export const CREATE_COMMISSION_FAILURE = "CREATE_COMMISSION_FAILURE";

export const UPDATE_COMMISSION = "UPDATE_COMMISSION";
export const UPDATE_COMMISSION_SUCCESS = "UPDATE_COMMISSION_SUCCESS";
export const UPDATE_COMMISSION_FAILURE = "UPDATE_COMMISSION_FAILURE";

export const DELETE_COMMISSION = "DELETE_COMMISSION";
export const DELETE_COMMISSION_SUCCESS = "DELETE_COMMISSION_SUCCESS";
export const DELETE_COMMISSION_FAILURE = "DELETE_COMMISSION_FAILURE";
