/**
 * Report Actions
 */
export const GET_REPORT_FAILURE = "GET_REPORT_FAILURE";

// Deal Report
export const GET_DEALS_BY_OWNER = "GET_DEALS_BY_OWNER";
export const GET_DEALS_BY_OWNER_SUCCESS = "GET_DEALS_BY_OWNER_SUCCESS";

export const GET_DEALS_BY_TYPE = "GET_DEALS_BY_TYPE";
export const GET_DEALS_BY_TYPE_SUCCESS = "GET_DEALS_BY_TYPE_SUCCESS";

export const GET_DEALS_PIPELINE = "GET_DEALS_PIPELINE";
export const GET_DEALS_PIPELINE_SUCCESS = "GET_DEALS_PIPELINE_SUCCESS";

// Lead Report
export const GET_LEADS_BY_STATUS = "GET_LEADS_BY_STATUS";
export const GET_LEADS_BY_STATUS_SUCCESS = "GET_LEADS_BY_STATUS_SUCCESS";

export const GET_LEADS_BY_OWNER = "GET_LEADS_BY_OWNER";
export const GET_LEADS_BY_OWNER_SUCCESS = "GET_LEADS_BY_OWNER_SUCCESS";

export const GET_LEADS_BY_SOURCE = "GET_LEADS_BY_SOURCE";
export const GET_LEADS_BY_SOURCE_SUCCESS = "GET_LEADS_BY_SOURCE_SUCCESS";

// Acct Cust Report
export const GET_TOP_SPENDER_ACCOUNT = "GET_TOP_SPENDER_ACCOUNT";
export const GET_TOP_SPENDER_ACCOUNT_SUCCESS =
  "GET_TOP_SPENDER_ACCOUNT_SUCCESS";

export const GET_TOP_SPENDER_CUSTOMER = "GET_TOP_SPENDER_CUSTOMER";
export const GET_TOP_SPENDER_CUSTOMER_SUCCESS =
  "GET_TOP_SPENDER_CUSTOMER_SUCCESS";

// Individual Report
export const GET_INDIVIDUAL_REPORT = "GET_INDIVIDUAL_REPORT";
export const GET_INDIVIDUAL_REPORT_SUCCESS = "GET_INDIVIDUAL_REPORT_SUCCESS";

// Clsoed Deal Report
export const GET_CLOSED_BY_OWNER = "GET_CLOSED_BY_OWNER";
export const GET_CLOSED_BY_OWNER_SUCCESS = "GET_CLOSED_BY_OWNER_SUCCESS";
