// Get all Templates
export const GET_ALL_TEMPLATE = "GET_ALL_TEMPLATE";
export const GET_ALL_TEMPLATE_SUCCESS = "GET_ALL_TEMPLATE_SUCCESS";
export const GET_ALL_TEMPLATE_FAILURE = "GET_ALL_TEMPLATE_FAILURE";

//Create Campaign Email Template
export const ADD_TEMPLATE = "ADD_TEMPLATE";
export const ADD_TEMPLATE_SUCCESS = "ADD_TEMPLATE_SUCCESS";
export const ADD_TEMPLATE_FAILURE = "ADD_TEMPLATE_FAILURE";

//Update Campaign Email Template
export const UPDATE_TEMPLATE = "UPDATE_TEMPLATE";
export const UPDATE_TEMPLATE_SUCCESS = "UPDATE_TEMPLATE_SUCCESS";
export const UPDATE_TEMPLATE_FAILURE = "UPDATE_TEMPLATE_FAILURE";
