// Get all Templates
export const GET_ALL_TEMPLATE = "GET_ALL_TEMPLATE";
export const GET_ALL_TEMPLATE_SUCCESS = "GET_ALL_TEMPLATE_SUCCESS";
export const GET_ALL_TEMPLATE_FAILURE = "GET_ALL_TEMPLATE_FAILURE";

//Create Campaign Email Template
export const ADD_TEMPLATE = "ADD_TEMPLATE";
export const ADD_TEMPLATE_SUCCESS = "ADD_TEMPLATE_SUCCESS";
export const ADD_TEMPLATE_FAILURE = "ADD_TEMPLATE_FAILURE";

//Update Campaign Email Template
export const UPDATE_TEMPLATE = "UPDATE_TEMPLATE";
export const UPDATE_TEMPLATE_SUCCESS = "UPDATE_TEMPLATE_SUCCESS";
export const UPDATE_TEMPLATE_FAILURE = "UPDATE_TEMPLATE_FAILURE";

//HUTTONMS 
//delete email template
export const DELETE_TEMPLATE = "DELETE_TEMPLATE";
export const DELETE_TEMPLATE_SUCCESS = "DELETE_TEMPLATE_SUCCESS";
export const DELETE_TEMPLATE_FAILURE = "DELETE_TEMPLATE_FAILURE";

//content update
export const UPDATE_EMAIL_CONTENT = "UPDATE_EMAIL_CONTENT";

//Update Campaign Email Template
export const UPDATE_TEMPLATE_TITLE = "UPDATE_TEMPLATE_TITLE";
export const UPDATE_TEMPLATE_TITLE_SUCCESS = "UPDATE_TEMPLATE_TITLE_SUCCESS";
export const UPDATE_TEMPLATE_TITLE_FAILURE = "UPDATE_TEMPLATE_TITLE_FAILURE";

export const GET_FILTER_TEMPLATE = "GET_FILTER_TEMPLATE";
export const GET_FILTER_TEMPLATE_SUCCESS = "GET_FILTER_TEMPLATE_SUCCESS";
export const GET_FILTER_TEMPLATE_FAILURE = "GET_FILTER_TEMPLATE_FAILURE";