export const GET_RECENT_BOOKINGS = "GET_RECENT_BOOKINGS";
export const GET_RECENT_BOOKINGS_SUCCESS = "GET_RECENT_BOOKINGS_SUCCESS";
export const GET_RECENT_BOOKINGS_FAILURE = "GET_RECENT_BOOKINGS_FAILURE";

export const GET_BOOKINGS = "GET_BOOKINGS";
export const GET_BOOKINGS_SUCCESS = "GET_BOOKINGS_SUCCESS";
export const GET_BOOKINGS_FAILURE = "GET_BOOKINGS_FAILURE";

export const UPDATE_BOOKING_STATUS = "UPDATE_BOOKING_STATUS";
export const UPDATE_BOOKING_STATUS_SUCCESS = "UPDATE_BOOKING_STATUS_SUCCESS";
export const UPDATE_BOOKING_STATUS_FAILURE = "UPDATE_BOOKING_STATUS_FAILURE";
