export const GET_RECENT_BOOKINGS = "GET_RECENT_BOOKINGS";
export const GET_RECENT_BOOKINGS_SUCCESS = "GET_RECENT_BOOKINGS_SUCCESS";
export const GET_RECENT_BOOKINGS_FAILURE = "GET_RECENT_BOOKINGS_FAILURE";
