/**
 * Quotation Actions
 */
// List
export const QUOTATION_LIST_DROPDOWN = "QUOTATION_LIST_DROPDOWN";
export const TOGGLE_QUOTATION_SUMMARY = "TOGGLE_QUOTATION_SUMMARY";
export const CHANGE_QUOTATION_LIST_VIEW = "CHANGE_QUOTATION_LIST_VIEW";
export const GET_QUOTATION_FAILURE = "GET_QUOTATION_FAILURE";
export const GET_QUOTATION_SUCCESS = "GET_QUOTATION_SUCCESS";
export const GET_ALL_QUOTATION = "GET_ALL_QUOTATION";
export const GET_MY_QUOTATION = "GET_MY_QUOTATION";
export const GET_OPEN_QUOTATION = "GET_OPEN_QUOTATION";
export const GET_CLOSED_QUOTATION = "GET_CLOSED_QUOTATION";

// List Summary
export const GET_QUOTE_SUMMARY = "GET_QUOTE_SUMMARY";
export const GET_QUOTE_SUMMARY_SUCCESS = "GET_QUOTE_SUMMARY_SUCCESS";
export const GET_QUOTE_SUMMARY_FAILURE = "GET_QUOTE_SUMMARY_FAILURE";

// View
export const GET_SINGLE_QUOTATION = "GET_SINGLE_QUOTATION";
export const GET_SINGLE_QUOTATION_SUCCESS = "GET_SINGLE_QUOTATION_SUCCESS";
export const CLEAR_SINGLE_QUOTATION = "CLEAR_SINGLE_QUOTATION";

// New
export const CLEAR_QUOTATION_FORM = "CLEAR_QUOTATION_FORM";
export const SUBMIT_QUOTATION = "SUBMIT_QUOTATION";
export const SUBMIT_QUOTATION_SUCCESS = "SUBMIT_QUOTATION_SUCCESS";
export const SUBMIT_QUOTATION_FAILURE = "SUBMIT_QUOTATION_FAILURE";


export const DELETE_QUOTATION = "DELETE_QUOTATION";
export const DELETE_QUOTATION_SUCCESS = "DELETE_QUOTATION_SUCCESS";
export const DELETE_QUOTATION_FAILURE = "DELETE_QUOTATION_FAILURE";

// Products List
export const ADD_NEW_PRODUCT_QUOTATION = "ADD_NEW_PRODUCT_QUOTATION";
export const REMOVE_PRODUCT_QUOTATION = "REMOVE_PRODUCT_QUOTATION";

// Handle Change
export const HANDLE_CHANGE_QUOTATION = "HANDLE_CHANGE_QUOTATION";
export const HANDLE_PRODUCT_QUOTATION = "HANDLE_PRODUCT_QUOTATION";
export const HANDLE_RELATED_TO_QUOTATION = "HANDLE_RELATED_TO_QUOTATION";
export const HANDLE_ATTN_TO_QUOTATION = "HANDLE_ATTN_TO_QUOTATION";
export const HANDLE_DISCOUNT_TAX_QUOTATION = "HANDLE_DISCOUNT_TAX_QUOTATION";

// Notes
export const ADD_NOTE_QUOTATION = "ADD_NOTE_QUOTATION";
export const ADD_NOTE_QUOTATION_SUCCESS = "ADD_NOTE_QUOTATION_SUCCESS";
export const ADD_NOTE_QUOTATION_FAILURE = "ADD_NOTE_QUOTATION_FAILURE";

// States
export const HANDLE_STATE_UPDATE = "HANDLE_STATE_UPDATE";
export const HANDLE_STATE_UPDATE_SUCCESS = "HANDLE_STATE_UPDATE_SUCCESS";
export const HANDLE_STATE_UPDATE_FAILURE = "HANDLE_STATE_UPDATE_FAILURE";

// Create New Version
export const HANDLE_STATE_CREATE_NEW_VERSION = "HANDLE_STATE_CREATE_NEW_VERSION";

// Revert Previous Version
export const HANDLE_STATE_REVERT_PREVIOUS_VERSION = "HANDLE_STATE_REVERT_PREVIOUS_VERSION";

// Convert quotation to invoice
export const HANDLE_STATE_CONVERT_INVOICE_QUOTATION = "HANDLE_STATE_CONVERT_INVOICE_QUOTATION";

export const HANDLE_QUOTATION_ACCOUNTS = "HANDLE_QUOTATION_ACCOUNTS";
export const HANDLE_QUOTATION_ACCOUNTS_SUCCESS = "HANDLE_QUOTATION_ACCOUNTS_SUCCESS";
export const HANDLE_QUOTATION_ACCOUNTS_FAILTURE = "HANDLE_QUOTATION_ACCOUNTS_FAILTURE";


export const SUBMIT_NEW_QUOTATION = "SUBMIT_NEW_QUOTATION";
export const SUBMIT_NEW_QUOTATION_SUCCESS = "SUBMIT_NEW_QUOTATION_SUCCESS";
export const SUBMIT_NEW_QUOTATION_FAILURE = "SUBMIT_NEW_QUOTATION_FAILURE";

export const RESTART_QUOTATION_UPLOAD_STATUS = "RESTART_QUOTATION_UPLOAD_STATUS";

