export const GET_ALL_COE = "GET_ALL_COE";
export const GET_ALL_COE_SUCCESS = "GET_ALL_COE_SUCCESS";
export const GET_ALL_COE_FAILURE = "GET_ALL_COE_FAILURE";

export const CREATE_COE = "CREATE_COE";
export const CREATE_COE_SUCCESS = "CREATE_COE_SUCCESS";
export const CREATE_COE_FAILURE = "CREATE_COE_FAILURE";

export const EDIT_COE = "EDIT_COE";
export const EDIT_COE_SUCCESS = "EDIT_COE_SUCCESS";
export const EDIT_COE_FAILURE = "EDIT_COE_FAILURE";

export const DELETE_COE = "DELETE_COE";
export const DELETE_COE_SUCCESS = "DELETE_COE_SUCCESS";
export const DELETE_COE_FAILURE = "DELETE_COE_FAILURE";

export const GET_ALL_WARRANTY = "GET_ALL_WARRANTY";
export const GET_ALL_WARRANTY_SUCCESS = "GET_ALL_WARRANTY_SUCCESS";
export const GET_ALL_WARRANTY_FAILURE = "GET_ALL_WARRANTY_FAILURE";

export const CREATE_WARRANTY = "CREATE_WARRANTY";
export const CREATE_WARRANTY_SUCCESS = "CREATE_WARRANTY_SUCCESS";
export const CREATE_WARRANTY_FAILURE = "CREATE_WARRANTY_FAILURE";

export const EDIT_WARRANTY = "EDIT_WARRANTY";
export const EDIT_WARRANTY_SUCCESS = "EDIT_WARRANTY_SUCCESS";
export const EDIT_WARRANTY_FAILURE = "EDIT_WARRANTY_FAILURE";

export const DELETE_WARRANTY = "DELETE_WARRANTY";
export const DELETE_WARRANTY_SUCCESS = "DELETE_WARRANTY_SUCCESS";
export const DELETE_WARRANTY_FAILURE = "DELETE_WARRANTY_FAILURE";

export const GET_ALL_SERVICING = "GET_ALL_SERVICING";
export const GET_ALL_SERVICING_SUCCESS = "GET_ALL_SERVICING_SUCCESS";
export const GET_ALL_SERVICING_FAILURE = "GET_ALL_SERVICING_FAILURE";

export const CREATE_SERVICING = "CREATE_SERVICING";
export const CREATE_SERVICING_SUCCESS = "CREATE_SERVICING_SUCCESS";
export const CREATE_SERVICING_FAILURE = "CREATE_SERVICING_FAILURE";

export const EDIT_SERVICING = "EDIT_SERVICING";
export const EDIT_SERVICING_SUCCESS = "EDIT_SERVICING_SUCCESS";
export const EDIT_SERVICING_FAILURE = "EDIT_SERVICING_FAILURE";

export const DELETE_SERVICING = "DELETE_SERVICING";
export const DELETE_SERVICING_SUCCESS = "DELETE_SERVICING_SUCCESS";
export const DELETE_SERVICING_FAILURE = "DELETE_SERVICING_FAILURE";