// Mini configurator
export const GET_GRADES = "GET_GRADES";
export const GET_GRADES_SUCCESS = "GET_GRADES_SUCCESS";
export const GET_GRADES_FAILURE = "GET_GRADES_FAILURE";

export const GET_EXTERIOR = "GET_EXTERIOR";
export const GET_EXTERIOR_SUCCESS = "GET_EXTERIOR_SUCCESS";
export const GET_EXTERIOR_FAILURE = "GET_EXTERIOR_FAILURE";

export const GET_INTERIOR = "GET_INTERIOR";
export const GET_INTERIOR_SUCCESS = "GET_INTERIOR_SUCCESS";
export const GET_INTERIOR_FAILURE = "GET_INTERIOR_FAILURE";

export const GET_ACCESSORIES = "GET_ACCESSORIES";
export const GET_ACCESSORIES_SUCCESS = "GET_ACCESSORIES_SUCCESS";
export const GET_ACCESSORIES_FAILURE = "GET_ACCESSORIES_FAILURE";
