/**
 * CRM Summary
 */
export const GET_CRM_SUMMARY = "GET_CRM_SUMMARY";
export const GET_CRM_SUMMARY_SUCCESS = "GET_CRM_SUMMARY_SUCCESS";
export const GET_CRM_SUMMARY_FAILURE = "GET_CRM_SUMMARY_FAILURE";

/**
 * Untouched Leads
 */
export const GET_UNTOUCHED_LEADS = "GET_UNTOUCHED_LEADS";
export const GET_UNTOUCHED_LEADS_SUCCESS = "GET_UNTOUCHED_LEADS_SUCCESS";
export const GET_UNTOUCHED_LEADS_FAILURE = "GET_UNTOUCHED_LEADS_FAILURE";
