/**
 * CRM Summary
 */
export const GET_CRM_SUMMARY = "GET_CRM_SUMMARY";
export const GET_CRM_SUMMARY_SUCCESS = "GET_CRM_SUMMARY_SUCCESS";
export const GET_CRM_SUMMARY_FAILURE = "GET_CRM_SUMMARY_FAILURE";

/**
 * Untouched Leads
 */
export const GET_UNTOUCHED_LEADS = "GET_UNTOUCHED_LEADS";
export const GET_UNTOUCHED_LEADS_SUCCESS = "GET_UNTOUCHED_LEADS_SUCCESS";
export const GET_UNTOUCHED_LEADS_FAILURE = "GET_UNTOUCHED_LEADS_FAILURE";

export const GET_DEALS_BY_PRODUCT = "GET_DEALS_BY_PRODUCT";
export const GET_DEALS_BY_PRODUCT_SUCCESS = "GET_DEALS_BY_PRODUCT_SUCCESS";
export const GET_DEALS_BY_PRODUCT_FAILURE = "GET_DEALS_BY_PRODUCT_FAILURE";

