/**
 * Customer Actions
 */
// List
export const CHANGE_CUSTOMER_LIST_VIEW = "CHANGE_CUSTOMER_LIST_VIEW";
export const GET_CUSTOMER_FAILURE = "GET_CUSTOMER_FAILURE";
export const GET_CUSTOMER_SUCCESS = "GET_CUSTOMER_SUCCESS";
export const GET_ALL_CUSTOMER = "GET_ALL_CUSTOMER";
export const GET_MY_CUSTOMER = "GET_MY_CUSTOMER";
export const GET_OPEN_CUSTOMER = "GET_OPEN_CUSTOMER";

// View
export const GET_SINGLE_CUSTOMER = "GET_SINGLE_CUSTOMER";
export const GET_SINGLE_CUSTOMER_SUCCESS = "GET_SINGLE_CUSTOMER_SUCCESS";
export const CLEAR_SINGLE_CUSTOMER = "CLEAR_SINGLE_CUSTOMER";

// New
export const NEW_CUSTOMER = "NEW_CUSTOMER";
export const NEW_CUSTOMER_SUCCESS = "NEW_CUSTOMER_SUCCESS";
export const NEW_CUSTOMER_FAILURE = "NEW_CUSTOMER_FAILURE";

// Edit
export const EDIT_CUSTOMER = "EDIT_CUSTOMER";
export const EDIT_CUSTOMER_SUCCESS = "EDIT_CUSTOMER_SUCCESS";
export const EDIT_CUSTOMER_FAILURE = "EDIT_CUSTOMER_FAILURE";

// Form Fields
export const GET_CUSTOMER_FORM_FIELDS = "GET_CUSTOMER_FORM_FIELDS";
export const GET_CUSTOMER_FORM_SUCCESS = "GET_CUSTOMER_FORM_SUCCESS";
export const GET_CUSTOMER_FORM_FAILURE = "GET_CUSTOMER_FORM_FAILURE";

// Notes
export const ADD_NOTE_CUSTOMER = "ADD_NOTE_CUSTOMER";
export const ADD_NOTE_CUSTOMER_SUCCESS = "ADD_NOTE_CUSTOMER_SUCCESS";
export const ADD_NOTE_CUSTOMER_FAILURE = "ADD_NOTE_CUSTOMER_FAILURE";

// Delete
export const DELETE_CUSTOMER = "DELETE_CUSTOMER";
export const DELETE_CUSTOMER_SUCCESS = "DELETE_CUSTOMER_SUCCESS";
export const DELETE_CUSTOMER_FAILURE = "DELETE_CUSTOMER_FAILURE";

// Set Active
export const SET_CUSTOMER_ACTIVE = "SET_CUSTOMER_ACTIVE";
export const SET_CUSTOMER_ACTIVE_SUCCESS = "SET_CUSTOMER_ACTIVE_SUCCESS";
export const SET_CUSTOMER_ACTIVE_FAILURE = "SET_CUSTOMER_ACTIVE_FAILURE";

// Transfer
export const TRANSFER_CUSTOMER = "TRANSFER_CUSTOMER";
export const TRANSFER_CUSTOMER_SUCCESS = "TRANSFER_CUSTOMER_SUCCESS";
export const TRANSFER_CUSTOMER_FAILURE = "TRANSFER_CUSTOMER_FAILURE";

// Event
export const ADD_CUSTOMER_EVENT = "ADD_CUSTOMER_EVENT";
